name: Android CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Generate build number
      id: buildnumber
      uses: onyxmueller/build-tag-number@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prefix: 'android'
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Update version code and name
      run: |
        echo "Build number: ${{ steps.buildnumber.outputs.build_number }}"
        sed -i "s/versionCode = .*/versionCode = ${{ steps.buildnumber.outputs.build_number }}/g" app/build.gradle.kts
        sed -i "s/versionName = .*/versionName = \"1.0.${{ steps.buildnumber.outputs.build_number }}\"/g" app/build.gradle.kts
    
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-${{ steps.buildnumber.outputs.build_number }}
        path: app/build/outputs/apk/release/app-release.apk
    
    - name: Create Release
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "app/build/outputs/apk/release/app-release.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v1.0.${{ steps.buildnumber.outputs.build_number }}
        name: Release v1.0.${{ steps.buildnumber.outputs.build_number }}
        body: |
          Автоматическая релизная сборка из ветки master
          
          Номер сборки: ${{ steps.buildnumber.outputs.build_number }}
          Коммит: ${{ github.sha }}
          
          Примечание: Эта сборка использует релизную конфигурацию с дебажной подписью.
        draft: false
        prerelease: false
        makeLatest: true 
